
package com.training.prodsvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServiceImpl", targetNamespace = "http://prodsvc.training.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServiceImpl {


    /**
     * 
     * @param prod
     */
    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.AddProductResponse")
    public void addProduct(
        @WebParam(name = "prod", targetNamespace = "http://prodsvc.training.com")
        Product prod);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProdInfoReturn", targetNamespace = "http://prodsvc.training.com")
    @RequestWrapper(localName = "getProdInfo", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.GetProdInfo")
    @ResponseWrapper(localName = "getProdInfoResponse", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.GetProdInfoResponse")
    public String getProdInfo();

}
